<template>
  <div>
    <div class="row">
      <div class="col-12">
        <ContentLoader
          :height="50"
          primary-color="#d7d9db"
        >
          <rect
            x="15"
            y="20"
            rx="3"
            ry="3"
            width="100"
            height="11"
          />
        </ContentLoader>
        <ContentLoader
          primary-color="#d7d9db"
        >
          <rect
            x="20"
            y="0"
            rx="3"
            ry="3"
            width="20"
            height="10"
          />
          <rect
            x="70"
            y="0"
            rx="3"
            ry="3"
            width="35"
            height="10"
          />
          <rect
            x="135"
            y="0"
            rx="3"
            ry="3"
            width="55"
            height="10"
          />
          <rect
            x="220"
            y="0"
            rx="3"
            ry="3"
            width="55"
            height="10"
          />
          <rect
            x="300"
            y="0"
            rx="3"
            ry="3"
            width="60"
            height="10"
          />
          <!-- Start Column Rect 1 -->
          <rect
            x="25"
            y="50"
            rx="3"
            ry="3"
            width="10"
            height="6"
          />
          <rect
            x="25"
            y="30"
            rx="3"
            ry="3"
            width="10"
            height="6"
          />
          <rect
            x="25"
            y="70"
            rx="3"
            ry="3"
            width="10"
            height="6"
          />
          <rect
            x="25"
            y="90"
            rx="3"
            ry="3"
            width="10"
            height="6"
          />
          <rect
            x="25"
            y="110"
            rx="3"
            ry="3"
            width="10"
            height="6"
          />
          <!-- End Colum Rect 1 -->
          <!-- Start Column Rect 2 -->
          <rect
            x="74"
            y="30"
            rx="3"
            ry="3"
            width="28"
            height="6"
          />
          <rect
            x="74"
            y="50"
            rx="3"
            ry="3"
            width="28"
            height="6"
          />
          <rect
            x="74"
            y="70"
            rx="3"
            ry="3"
            width="28"
            height="6"
          />
          <rect
            x="74"
            y="90"
            rx="3"
            ry="3"
            width="28"
            height="6"
          />
          <rect
            x="74"
            y="110"
            rx="3"
            ry="3"
            width="28"
            height="6"
          />
          <!-- End Column Rect 2 -->
          <!-- Start Column Rect 3 -->
          <rect
            x="145"
            y="30"
            rx="3"
            ry="3"
            width="35"
            height="6"
          />
          <rect
            x="145"
            y="50"
            rx="3"
            ry="3"
            width="35"
            height="6"
          />
          <rect
            x="145"
            y="70"
            rx="3"
            ry="3"
            width="35"
            height="6"
          />
          <rect
            x="145"
            y="90"
            rx="3"
            ry="3"
            width="35"
            height="6"
          />
          <rect
            x="145"
            y="110"
            rx="3"
            ry="3"
            width="35"
            height="6"
          />
          <!-- End Column Rect 3 -->
          <!-- Start Column Rect 4 -->
          <rect
            x="230"
            y="30"
            rx="3"
            ry="3"
            width="35"
            height="6"
          />
          <rect
            x="230"
            y="50"
            rx="3"
            ry="3"
            width="35"
            height="6"
          />
          <rect
            x="230"
            y="70"
            rx="3"
            ry="3"
            width="35"
            height="6"
          />
          <rect
            x="230"
            y="90"
            rx="3"
            ry="3"
            width="35"
            height="6"
          />
          <rect
            x="230"
            y="110"
            rx="3"
            ry="3"
            width="35"
            height="6"
          />
          <!-- End Column Rect 4 -->
          <!-- Start Column Rect 5 -->
          <rect
            x="308"
            y="30"
            rx="3"
            ry="3"
            width="43"
            height="6"
          />
          <rect
            x="308"
            y="50"
            rx="3"
            ry="3"
            width="43"
            height="6"
          />
          <rect
            x="308"
            y="70"
            rx="3"
            ry="3"
            width="43"
            height="6"
          />
          <rect
            x="308"
            y="90"
            rx="3"
            ry="3"
            width="43"
            height="6"
          />
          <rect
            x="308"
            y="110"
            rx="3"
            ry="3"
            width="43"
            height="6"
          />
          <!-- End Column Rect 5 -->
        </ContentLoader>
      </div>
    </div>
  </div>
</template>

<script>
import { ContentLoader } from 'vue-content-loader'
export default {
  components: {
    ContentLoader
  },
  data () {
    return {
      v: 6
    }
  }
}
</script>

<style scoped>
</style>
